---
abstract: 'Multiplayer SocialCalc Server'
author:
  - '唐鳳 <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: CPAL
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SocialCalc-Multiplayer
no_index:
  directory:
    - inc
    - socialcalc
requires:
  File::ShareDir: 0
  Tatsumaki: 0
  perl: 5.6.0
resources:
  repository: http://github.com/audreyt/socialcalc
version: 20091118
